apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "2"
    openshift.io/deployment-config.name: iperf3
    openshift.io/deployment.name: iperf3-2
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/scc: anyuid
  creationTimestamp: 2019-01-08T06:39:20Z
  generateName: iperf3-2-
  labels:
    app: iperf3
    deployment: iperf3-2
    deploymentconfig: iperf3
  name: iperf3-2-j8jzb
  namespace: t-kafka-04
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: iperf3-2
    uid: 1eb5ef64-1310-11e9-893e-6c92bf025c32
  resourceVersion: "47731417"
  selfLink: /api/v1/namespaces/t-kafka-04/pods/iperf3-2-j8jzb
  uid: 210ea864-1310-11e9-893e-6c92bf025c32
spec:
  containers:
  - args:
    - -s
    image: networkstatic/iperf3@sha256:12c4ad04039b7dc7e5183984ea4dc7e2015b439b3b5c2c48f3993d425c3996d9
    imagePullPolicy: Always
    name: iperf3
    ports:
    - containerPort: 5201
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dgp7c
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-xj8r7
  nodeName: openshift-master3.cup.com
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000890000
    seLinuxOptions:
      level: s0:c30,c10
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-dgp7c
    secret:
      defaultMode: 420
      secretName: default-token-dgp7c
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-01-08T06:39:20Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-01-08T06:40:32Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-01-08T06:39:20Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://fba2bee7e0ba0d4f99f08496dc51551814fc725d89de7b7a8739db7c34c13410
    image: docker.io/networkstatic/iperf3@sha256:12c4ad04039b7dc7e5183984ea4dc7e2015b439b3b5c2c48f3993d425c3996d9
    imageID: docker-pullable://docker.io/networkstatic/iperf3@sha256:12c4ad04039b7dc7e5183984ea4dc7e2015b439b3b5c2c48f3993d425c3996d9
    lastState: {}
    name: iperf3
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-01-08T06:40:31Z
  hostIP: 172.16.25.125
  phase: Running
  podIP: 10.129.2.196
  qosClass: BestEffort
  startTime: 2019-01-08T06:39:20Z
