apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-70001
  name: proxy-70001
spec:
  clusterIP: 
  ports:
  - name: 9370-tcp
    port: 9370
    protocol: TCP
    targetPort: 9370
  selector:
    deploymentconfig: proxy-70001
  type: ClusterIP
