apiVersion: v1
kind: Service
metadata:
  labels:
    app: storage-70001
  name: storage-70001
spec:
  clusterIP: 
  ports:
  - name: 7778-tcp
    port: 7778
    protocol: TCP
    argetPort: 7778
  selector:
    deploymentconfig: egg-70001
  type: ClusterIP
