apiVersion: v1
kind: Service
metadata:
  labels:
    app: egg-70001
  name: egg-70001
spec:
  clusterIP: 
  ports:
  - name: 7888-tcp
    port: 7888
    protocol: TCP
    targetPort: 7888
  selector:
    deploymentconfig: egg-70001
  type: ClusterIP
