apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: egg-fateflow-storage-50001
  name: egg-fateflow-storage-50001
spec:
  replicas: 1
  selector:
    app: egg-fateflow-storage-50001
    deploymentconfig: egg-fateflow-storage-50001
  template:
    metadata:
      labels:
        app: egg-fateflow-storage-50001
        deploymentconfig: egg-fateflow-storage-50001
    spec:
      containers:
      - args:
        - mkdir -p /data/projects/fate/data-dir && sed -i "s/party.id=.*/party.id=${PARTY_ID}/g" ${EGG_PROPERTIES} && sed -i "s/roll-ip/172.30.11.90/g" ${SERVER_CONFIG_JSON} && sed -i "s/federation-ip/172.30.98.76/g" ${SERVER_CONFIG_JSON} && sed -i "s/fateflow-ip/${MY_POD_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/fateboard-ip/172.30.209.193/g" ${SERVER_CONFIG_JSON} && sed -i "s/proxy-ip/172.30.9.74/g" ${SERVER_CONFIG_JSON} && sed -i "s/serving-ip/172.30.252.215/g" ${SERVER_CONFIG_JSON} && sed -i "s/party-id/${PARTY_ID}/g" ${SERVER_CONFIG_JSON} && sed -i "s/party-id/${PARTY_ID}/g" ${SETTINGS} && sed -i "s/fateflow-ip/${MY_POD_IP}/g" ${SETTINGS} && sed -i "s/mysql-ip/172.30.76.31/g" ${SETTINGS} && sed -i "s/redis-ip/172.30.246.169/g" ${SETTINGS} && cd /data/projects/fate/storage-service-cxx && cd /data/projects/fate/storage-service-cxx && ./storage-service -p 7778 -d /data/projects/fate/data-dir >> logs/console.log 2>>logs/error.log
        command:
        - /bin/sh
        - -c
        env:
        - name: PARTY_ID
          value: "50001"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: EGG_PROPERTIES
          value: /data/projects/fate/egg/conf/egg.properties 
        - name: SERVER_CONFIG_JSON
          value: /data/projects/fate/python/arch/conf/server_conf.json
        - name: SETTINGS
          value: /data/projects/fate/python/fate_flow/settings.py
        - name: LOG_DIR
          value: /data/projects/fate/python/logs
        image: docker-repo.sonic.com:443/fate/egg-fateflow-storage:5.2
        imagePullPolicy: IfNotPresent
        name: egg-fateflow-storage-50001
