apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: fateboard-50001
  name: fateboard-50001
spec:
  replicas: 1
  selector:
    app: fateboard-50001
    deploymentconfig: fateboard-50001
  template:
    metadata:
      labels:
        app: fateboard-50001
        deploymentconfig: fateboard-50001
    spec:
      containers:
      - args:
        - sed -i "s#^spring.datasource.url=.*#spring.datasource.url=jdbc:mysql://${MYSQL_IP}:3306/${MYSQL_DATABASE}?characterEncoding=utf8\&characterSetResults=utf8\&autoReconnect=true\&failOverReadOnly=false\&serverTimezone=GMT%2B8#g"
          /data/projects/fate/fateboard/conf/application.properties &&sed -i "s#^fate.url=.*#fate.url=http://${MY_POD_IP}:9380#g"
          /data/projects/fate/fateboard/conf/application.properties && echo ${MY_POD_IP}
          >> aaa && echo ${PARTY_ID} >> aaa && java -Dspring.config.location=$configpath/application.properties
          -Dssh_config_file=$configpath -Xmx2048m -Xms2048m -XX:+PrintGCDetails -XX:+PrintGCDateStamps
          -Xloggc:gc.log -XX:+HeapDumpOnOutOfMemoryError  -jar $basepath/fateboard.jar
          >/dev/null 2>&1
        command:
        - /bin/sh
        - -c
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PARTY_ID
          value: "50001"
        - name: MYSQL_IP
          value: 172.30.76.31
        - name: MYSQL_DATABASE
          value: fateflowdb
        image: docker-repo.sonic.com:443/fate/fateboard:5.1
        imagePullPolicy: IfNotPresent
        name: fateboard-50001
