apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: serving-server-50001
  name: serving-server-50001
spec:
  replicas: 1
  selector:
    app: serving-server-50001
    deploymentconfig: serving-server-50001
  template:
    metadata:
      labels:
        app: serving-server-50001
        deploymentconfig: serving-server-50001
    spec:
      containers:
      - args:
        - sed -i "s/party-id/${PARTY-ID}/g" ${SERVING_SERVER_PROPERTIES} && sed -i "s/serving-server-ip/${MY_POD_IP}/g" ${SERVING_SERVER_PROPERTIES} && sed -i "s/redis-ip/172.30.246.169/g" ${SERVING_SERVER_PROPERTIES} && sed -i "s/proxy-ip/172.30.9.74/g" ${SERVING_SERVER_PROPERTIES}  && sed -i "s/roll-ip/172.30.11.90/g" ${SERVING_SERVER_PROPERTIES} && java -cp "conf/:lib/*:fate-serving-server.jar" com.webank.ai.fate.serving.ServingServer -c conf/serving-server.properties >> logs/console.log 2>>logs/error.log
        command:
        - /bin/sh
        - -c
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PARTY_ID
          value: "50001"
        - name: SERVING_SERVER_PROPERTIES
          value: /data/projects/fate/serving-server/conf/serving-server.properties
        image: docker-repo.sonic.com:443/fate/serving-server:5.1
        imagePullPolicy: IfNotPresent
        name: serving-server-50001
