apiVersion: v1
kind: Service
metadata:
  labels:
    app: serving-server-50001
  name: serving-server-50001
spec:
  clusterIP: 
  ports:
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    deploymentconfig: serving-server-50001
  type: ClusterIP
