apiVersion: v1
kind: Service
metadata:
  labels:
    app: egg-fateflow-storage-50001
  name: egg-fateflow-storage-50001
spec:
  clusterIP: 
  ports:
  - name: 7888-tcp
    port: 7888
    protocol: TCP
    targetPort: 7888
  - name: 9360-tcp
    port: 9360
    protocol: TCP
    targetPort: 9360
  - name: 9380-tcp
    port: 9380
    protocol: TCP
    targetPort: 9380
  - name: 7778-tcp
    port: 7778
    protocol: TCP
    targetPort: 7778
  selector:
    deploymentconfig: egg-fateflow-storage-50001
  type: ClusterIP
