#!/bin/bash

# move the application source
rm -rf /usr/local/tomcat/webapps/ROOT
rm -f /usr/local/tomcat/webapps/ROOT.war
cp /tmp/src/ROOT.war /usr/local/tomcat/webapps/ROOT.war
echo '111' > /tmp/src/test
#mv /tmp/src/*.war /usr/local/tomcat/webapps/
#mv /tmp/src/server.xml /usr/local/tomcat/conf/
#mv /tmp/src/tomcat-users.xml /usr/local/tomcat/conf/
