apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs01
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /data/nfs/nfs01
    server: 10.33.14.136
  persistentVolumeReclaimPolicy: Recycle
