kind: Service
apiVersion: v1
metadata:
  name: mysql-nodeport-svc
spec:
  type: NodePort
  clusterIP:
  ports:
  - name: mysql
    port: 3306
  selector:
    v1alpha1.mysql.oracle.com/cluster: mysql-test-cluster

