apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: federation-50002
  name: federation-50002
spec:
  replicas: 1
  selector:
    app: federation-50002
    deploymentconfig: federation-50002
  template:
    metadata:
      labels:
        app: federation-50002
        deploymentconfig: federation-50002
    spec:
      containers:
      - args:
        - sed -i "s/party.id=.*/party.id=${PARTY-ID}/g" ${FEDERATION_PROPERTIES} && sed -i "s/meta-service-ip/${META_SERVICE_IP}/g" ${FEDERATION_PROPERTIES} && java -cp conf/:lib/*:fate-federation.jar com.webank.ai.fate.driver.Federation -c conf/federation.properties >> logs/console.log 2>>logs/error.log
        command:
        - /bin/sh
        - -c
        env:
        - name: PARTY_ID
          value: "50002"
        - name: META_SERVICE_IP
          value: 172.30.119.37 
        - name: FEDERATION_PROPERTIES
          value: /data/projects/fate/federation/conf/federation.properties
        image: docker-repo.sonic.com:443/fate/federation:5.1
        imagePullPolicy: IfNotPresent
        name: federation-50002
