apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-50002
  name: mysql-50002
spec:
  clusterIP: 
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deploymentconfig: mysql-50002
  type: ClusterIP
