apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-50002
  name: redis-50002
spec:
  clusterIP: 
  ports:
  - name: 6379-tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    deploymentconfig: redis-50002
  type: ClusterIP
