apiVersion: v1
kind: Service
metadata:
  labels:
    app: egg-70002
  name: egg-70002
spec:
  clusterIP: 
  ports:
  - name: 7888-tcp
    port: 7888
    protocol: TCP
    targetPort: 7888
  selector:
    deploymentconfig: egg-70002
  type: ClusterIP
