apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-70002
  name: proxy-70002
spec:
  clusterIP: 
  ports:
  - name: 9370-tcp
    port: 9370
    protocol: TCP
    targetPort: 9370
  selector:
    deploymentconfig: proxy-70002
  type: ClusterIP
