kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: mysql-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- my-admin-user
groups:
- my-admin-group
