server:
  port: 80

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mysql/lifeng
    username: lifeng
    password: lifeng
  redis:
    host: redis
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
    timeout: 1000




