apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: proxy-50001
  name: proxy-50001
spec:
  replicas: 1
  selector:
    app: proxy-50001
    deploymentconfig: proxy-50001
  template:
    metadata:
      labels:
        app: proxy-50001
        deploymentconfig: proxy-50001
    spec:
      containers:
      - args:
        - sed -i "s/party-id/${PARTY_ID}/g" ${PROXY_PROPERTIES} && sed -i "s/proxy-ip/${MY_POD_IP}/g" ${PROXY_PROPERTIES} && sed -i "s/host-proxy-ip/172.30.9.74/g" ${ROUTE_TABLE_JSON} && sed -i "s/host-party-id/50001/g" ${ROUTE_TABLE_JSON} && sed -i "s/federation-ip/172.30.98.76/g" ${ROUTE_TABLE_JSON} && sed -i "s/fateflow-ip/172.30.81.20/g" ${ROUTE_TABLE_JSON}  && sed -i "s/serving-ip/172.30.252.215/g" ${ROUTE_TABLE_JSON} && sed -i "s/guest-party-id/50002/g" ${ROUTE_TABLE_JSON} && sed -i "s/guest-proxy-ip/172.30.57.106/g" ${ROUTE_TABLE_JSON} && java -cp conf/:lib/*:fate-proxy.jar com.webank.ai.fate.networking.Proxy -c conf/proxy.properties >> logs/console.log 2>>logs/error.log
        command:
        - /bin/sh
        - -c
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PARTY_ID
          value: "50001"
        - name: PROXY_PROPERTIES
          value: /data/projects/fate/proxy/conf/proxy.properties
        - name: ROUTE_TABLE_JSON
          value: /data/projects/fate/proxy/conf/route_table.json
        - name: GUEST_PARTY_ID
          value: "50002"
        image: docker-repo.sonic.com:443/fate/proxy:5.1
        imagePullPolicy: IfNotPresent
        name: proxy-50001
