apiVersion: v1
kind: Service
metadata:
  labels:
    app: fateboard-60002
  name: fateboard-60002
spec:
  clusterIP: 
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: egg-fateflow-storage-60002 
  type: ClusterIP
