apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-60002
  name: redis-60002
spec:
  clusterIP: 
  ports:
  - name: 6379-tcp
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    deploymentconfig: redis-60002
  type: ClusterIP
