apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: egg-fateflow-storage-60001
  name: egg-fateflow-storage-60001
spec:
  replicas: 1
  selector:
    app: egg-fateflow-storage-60001
    deploymentconfig: egg-fateflow-storage-60001
  template:
    metadata:
      labels:
        app: egg-fateflow-storage-60001
        deploymentconfig: egg-fateflow-storage-60001
    spec:
      containers:
      - args:
        - sleep 3600000
        command:
        - /bin/sh
        - -c
        env:
        - name: PARTY_ID
          value: "60001"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker-repo.sonic.com:443/fate/egg-fateflow-storage:5.2
        imagePullPolicy: IfNotPresent
        name: egg-fateflow-storage-60001
