apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy-60001
  name: proxy-60001
spec:
  clusterIP: 
  ports:
  - name: 9370-tcp
    port: 9370
    protocol: TCP
    targetPort: 9370
  selector:
    deploymentconfig: egg-fateflow-storage-60001
  type: ClusterIP
