apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-60003
  name: mysql-60003
spec:
  clusterIP: 
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deploymentconfig: mysql-60003
  type: ClusterIP
