apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: fateflow-60003
  name: fateflow-60003
spec:
  replicas: 1
  selector:
    app: fateflow-60003
    deploymentconfig: fateflow-60003
  template:
    metadata:
      labels:
        app: fateflow-60003
        deploymentconfig: fateflow-60003
    spec:
      containers:
      - args:
        - sed -i "s/roll-ip/${ROLL_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/federation-ip/${FEDERATION_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/fateflow-ip/${MY_POD_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/fateboard-ip/${FATEBOARD_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/proxy-ip/${PROXY_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/serving-ip/${SERVING_IP}/g" ${SERVER_CONFIG_JSON} && sed -i "s/party-id/${PARTY_ID}/g" ${SERVER_CONFIG_JSON} && sed -i "s/party-id/${PARTY_ID}/g" ${SETTINGS} && sed -i "s/fateflow-ip/${MY_POD_IP}/g" ${SETTINGS} && sed -i "s/mysql-ip/${MYSQL_IP}/g" ${SETTINGS} && sed -i "s/redis-ip/${REDIS_IP}/g" ${SETTINGS} && sleep 360000 
        command:
        - /bin/sh
        - -c
        env:
        - name: PARTY_ID
          value: "60003"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ROLL_IP
          value: roll-60003
        - name: FEDERATION_IP
          value: federation-60003
        - name: FATEBOARD_IP
          value: fateboard-60003
        - name: PROXY_IP
          value: proxy-60003
        - name: MYSQL_IP
          value: mysql-60003
        - name: SERVING_IP
          value: serving-60003 
        - name: REDIS_IP
          value: redis-60003
        - name: SERVER_CONFIG_JSON
          value: /data/projects/fate/python/arch/conf/server_conf.json
        - name: SETTINGS
          value: /data/projects/fate/python/fate_flow/settings.py
        - name: LOG_DIR
          value: /data/projects/fate/python/logs
        image: docker-repo.sonic.com:443/fate/egg-fateflow-storage:5.2
        imagePullPolicy: IfNotPresent
        name: fateflow-60003

