apiVersion: v1
kind: Pod
metadata:
  name: kafka-client-06
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:5.0.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
    resources:
        limits:
          cpu: '16'
          memory: 32G
        requests:
          cpu: '16'
          memory: 32G
