apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper02
    deployment: zookeeper02-2
    deploymentconfig: zookeeper02
  name: zookeeper02-2-rs9xj
  namespace: t-kafka-01
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: zookeeper02-2
    uid: 3219f301-0745-11e9-893e-6c92bf025c32
  resourceVersion: "41750627"
  selfLink: /api/v1/namespaces/t-kafka-01/pods/zookeeper02-2-rs9xj
  uid: 4c164c06-0745-11e9-893e-6c92bf025c32
spec:
  containers:
  - image: zookeeper@sha256:1d80d9fb2f7986e9bb45c0daa2228097ed6fc8f6fbf4090ec756417ad9107a02
    imagePullPolicy: Always
    name: zookeeper02
    ports:
    - containerPort: 2181
      protocol: TCP
    - containerPort: 2888
      protocol: TCP
    - containerPort: 3888
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: zk02
    - mountPath: /datalog
      name: zookeeper02-2
    - mountPath: /logs
      name: zookeeper02-3
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lqghg
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-lrhxf
  nodeName: openshift-master1.cup.com
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000830000
    seLinuxOptions:
      level: s0:c29,c9
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: zk02
    persistentVolumeClaim:
      claimName: zk02
  - emptyDir: {}
    name: zookeeper02-2
  - emptyDir: {}
    name: zookeeper02-3
  - name: default-token-lqghg
    secret:
      defaultMode: 420
      secretName: default-token-lqghg
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-12-24T06:29:42Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-12-24T06:29:49Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-12-24T06:29:42Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://063f3bbe56bca2019f5cd68e064c26236142868fc4704a167604d901e2b87d5d
    image: docker.io/zookeeper@sha256:1d80d9fb2f7986e9bb45c0daa2228097ed6fc8f6fbf4090ec756417ad9107a02
    imageID: docker-pullable://docker.io/zookeeper@sha256:1d80d9fb2f7986e9bb45c0daa2228097ed6fc8f6fbf4090ec756417ad9107a02
    lastState: {}
    name: zookeeper02
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-12-24T06:29:49Z
  hostIP: 172.16.25.123
  phase: Running
  podIP: 10.131.0.26
  qosClass: BestEffort
  startTime: 2018-12-24T06:29:42Z
